default: &default
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1
  username: techmarket_user
  password: techmarket123
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: techmarket_oaxaca_api_development

test:
  <<: *default
  database: techmarket_oaxaca_api_test

production:
  <<: *default
  database: techmarket_oaxaca_api_production